
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "arugula");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "broccolii");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "brussels iSprouts");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "bruselas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "cabbage");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "repolyo");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "cauliflower");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "kolis");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "chinese Cabbage");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "pechay/ Petsay");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "daikon Radishes");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "puting Labanos");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "kale");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "kina");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "kohlrabi");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "mustard Greens");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "mustasa");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "radishes");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "labanos");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "turnips");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "turnip Greens");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Brassicas Family", "singkamas");



INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "Beets");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "Remolatsa");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "Spinach");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "Kangkong");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "Swiss Chard");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "Malabar Spinach");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "Alugbati");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "beets");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "remolatsa");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "spinach");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "kangkong");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "swiss Chard");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "malabar Spinach");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Chenopodiaceae Family", "alugbati");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Poaceae Family", "Corn");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Poaceae Family", "Mais");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Poaceae Family", "Grains");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Poaceae Family", "Palay");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Poaceae Family", "corn");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Poaceae Family", "mais");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Poaceae Family", "grains");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Poaceae Family", "palay");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "Beans");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "Patani");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "Peanuts");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "Mani");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "Peas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "Gisantes");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "beans");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "patani");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "peanuts");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "mani");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "peas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Fabaceae Family", "gisantes");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Artichoke");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Alkatsopas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Endive");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Tsikorya/ Endiba");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Escarole");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Escarola");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Lettuce");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Letsugas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Sunflower");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "Mirasol");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "artichoke");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "alkatsopas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "endive");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "tsikorya/ Endiba");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "escarole");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "escarola");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "lettuce");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "letsugas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "sunflower");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Compositae Family", "mirasol");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Cantaloupes");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Melon");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Katimon");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Cucumbers");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Pipino");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Gourds");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Kalabasang Ligaw");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Melons");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Milon");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Pumpkins");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Kalabasa");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Summer Squash");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Kukurbita");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Watermelon");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Pakwan");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Winter Squash");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Kandoy");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Zucchini");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "Sukini");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "cantaloupes");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "melon");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "katimon");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "cucumbers");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "pipino");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "gourds");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "kalabasang ligaw");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "melons");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "milon");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "pumpkins");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "kalabasa");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "summer squash");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "kukurbita");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "watermelon");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "pakwan");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "winter Squash");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "kandoy");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "zucchini");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Cucurbitaceae Family", "sukini");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Convolvulaceae Family", "Sweet Potato");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Convolvulaceae Family", "Kamote");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Convolvulaceae Family", "sweet potato");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Convolvulaceae Family", "kamote");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Eggplant");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Talong");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Peppers");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Paminta");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Potatoes");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Patatas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Tomatoes");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Tomato");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Kamatis");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Chili");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "Sili");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "eggplant");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "talong");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "peppers");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "paminta");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "potatoes");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "patatas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "tomatoes");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "tomato");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "kamatis");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "chili");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Solanaceae Family", "sili");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "Chives");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "Kutsay");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "Garlic");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "Bawang");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "Leeks");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "Dahon ng Sibuyas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "Onions");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "Onion");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "Sibuyas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "chives");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "kutsay");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "kintsay");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "garlic");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "bawang");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "leeks");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "dahon ng Sibuyas");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "onions");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "onion");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Amaryllidaceae Family", "sibuyas");

INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Carrot");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Karot");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Celery");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Kintsay");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Cilantro");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Silantro");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Kulantro");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Dill");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Eneldo");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Fennel");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Haras");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Parsley");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Parehil");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Labanos");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "Parsnip");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "carrot");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "karot");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "celery");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "kintsay");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "cilantro");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "silantro");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "kulantro");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "dill");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "eneldo");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "fennel");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "haras");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "parsley");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "parehil");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "labanos");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Umbelliferae Family", "parsnip");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Arecaceae Family", "Coconut");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Arecaceae Family", "Niyog");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Arecaceae Family", "coconut");
INSERT INTO botanicfam (botanical_family, botanicfam_crops) VALUES ("Arecaceae Family", "niyog");




